name = "Lmo Web"
author_name = "Joren Hammudoglu"
author_email = "jhammudoglu@gmail.com"
license = "BSD-3-Clause"

interpreter = "0.26.0a4"
packages = [
    "plotly>=5.20,<6.0",
    "scipy>=1.12,<2.0",
    "Lmo>=0.13.0,<1.0",
]

[files]
"{FROM}" = "https://jorenham.github.io/Lmo-web/lmo_web"
"{TO}" = "./lmo_web"
"{FROM}/web_storage.py" = "{TO}/web_storage.py"
