name = "Lmo Web"
author_name = "Joren Hammudoglu"
author_email = "jhammudoglu@gmail.com"
license = "BSD-3-Clause"

interpreter = "0.27.0a2"
packages = [
    "plotly>=5.24,<6.0",
    "scipy>=1.13.1,<2.0",
    "Lmo>=0.14.2,<1.0",
]

[files]
"{FROM}" = "https://jorenham.github.io/Lmo-web/lmo_web"
"{TO}" = "./lmo_web"
"{FROM}/web_storage.py" = "{TO}/web_storage.py"
