name = "Lmo Web"
interpreter = "0.24.1"
packages = [
    "plotly>=5.18,<6.0",
    "scipy>=1.11,<2.0",
    "Lmo>=0.12,<1.0",
]

[files]
"{FROM}" = "/lmo_web"
"{TO}" = "./lmo_web/"
"{FROM}/__init__.py" = "{TO}"
"{FROM}/web_storage.py" = "{TO}"
